dahromy_glide:
    source:
        source: '%kernel.project_dir%/public/images'
        source_path_prefix: '/images'
    cache:
        cache: '%kernel.project_dir%/var/cache/glide'
        cache_path_prefix: '/cache'
        temp_dir: '%kernel.project_dir%/var/tmp/glide'
        group_cache_in_folders: true
        cache_with_file_extensions: true
    watermarks:
        watermarks: '%kernel.project_dir%/public/watermarks'
        watermarks_path_prefix: '/watermarks'
    driver: 'gd'  # or 'imagick'
    max_image_size: '2000*2000'
    defaults:
        q: 90
        fm: 'auto'
        fit: 'contain'
    presets:
        thumbnail:
            w: 200
            h: 200
            fit: 'crop'
        medium:
            w: 600
            h: 400
            fit: 'contain'
        watermarked:
            mark: 'logo.png'
            markw: 100
            markpos: 'bottom-right'
            markalpha: 50
