dahromy_glide:
    source: '%kernel.project_dir%/public/uploads'
    cache: '%kernel.project_dir%/var/cache/glide'
    signature_key: '%env(GLIDE_SIGNATURE_KEY)%'
    driver: 'gd'
    max_image_size: 2000*2000
    base_url: '/images/'
    defaults:
        q: 80
        fm: 'jpg'
    presets:
        small_thumbnail:
            w: 200
            h: 200
            fit: 'crop'
        medium:
            w: 600
            dpr: 2
